# Set the base image
FROM alpine

# redeclipse tag
ARG TAG
# redeclipse commit sha
ARG RE_COMMIT
# alpine base sha
ARG ALPINE_SHA
# dockerfile sha
ARG DOCKERFILE_SHA

# information
LABEL author="Iceflower S"
LABEL maintainer="Iceflower S"
LABEL email="iceflower@gmx.de"
LABEL description="Red Eclipse Server - $TAG"
LABEL re-tag="$TAG"
LABEL re-commit="$RE_COMMIT"
LABEL alpine-sha="$ALPINE_SHA"
LABEL dockerfile-sha="$DOCKERFILE_SHA"

# Add server user and set permissions
RUN adduser -S -D redeclipse \
    && mkdir /redeclipse \
    && chown redeclipse: -R /redeclipse

# Update application repository list, create build dir, build server, move server files, create other permanent files and clean up
RUN echo "@edge-testing https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk update \
    && apk add --no-cache --virtual build-deps gcc g++ zlib-dev openal-soft-dev libsndfile-dev git ca-certificates freetype-dev coreutils cmake make \
    && apk add --no-cache freealut-dev@edge-testing \
    && apk add --no-cache libstdc++ \
    && git clone --depth 1 -b "$TAG" https://github.com/redeclipse/base /temp \
    \
    && mkdir -p /redeclipse/bin/native \
    && cd /temp \
    && make INSTDIR="/redeclipse/bin/native/" CFLAGS="-m64 -O3 -fomit-frame-pointer -ffast-math -fno-finite-math-only" CXXFLAGS="-m64 -O3 -fomit-frame-pointer -ffast-math -fno-finite-math-only" LDFLAGS="-m64" -O -j 4 -C src install-server \
    \
    && mkdir -p /redeclipse/config \
    && mv /temp/config/ /redeclipse/ \
    \
    && cd /temp \
    && git submodule update --init ./data/maps/ \
    && rm -rf ./data/maps/.git/ \
    && mkdir -p /redeclipse/data/maps \
    && mv /temp/data/maps/* /redeclipse/data/maps/ \
    \
    && apk update \
    && apk del build-deps \
    && apk del freealut-dev \
    && rm -rf /temp/

# Add folder
RUN mkdir -p /re-server-config/home \
    && mkdir -p /re-server-config/package

USER redeclipse

WORKDIR /redeclipse
ENTRYPOINT ["./bin/native/redeclipse_server_linux", "-h/re-server-config/home/", "-p/re-server-config/package/"]
