# Set the base image
FROM alpine

# redeclipse branch
ARG BRANCH
# redeclipse commit
ARG RECOMMIT

# informations
LABEL author="Iceflower S" \
      maintainer="Iceflower S" \
      email="iceflower@gmx.de" \
      version="1.0" \
      description="Red Eclipse Server - $BRANCH" \
      re-commit="$RECOMMIT"

# Add server user and set permissions
RUN adduser -S -D redeclipse \
    && mkdir /redeclipse \
    && chown redeclipse: -R /redeclipse

# Update application repository list, create build dir, build server, move server files, create other permanent files and clean up
RUN apk update \
    && apk add --no-cache --virtual build-deps gcc g++ zlib-dev git ca-certificates coreutils cmake make sdl2_image-dev sdl2_mixer-dev \
    && apk add --no-cache libstdc++ \
    && git clone --depth 1 -b "$BRANCH" https://github.com/redeclipse/base /temp \
    \
    && cd /temp \
    && make -C src -j"$(nproc)" redeclipse_server_linux install-server WANT_STEAM=0 WANT_DISCORD=0 \
    \
    && mkdir -p /redeclipse/config \
    && mv /temp/config/ /redeclipse/ \
    && mkdir -p /redeclipse/bin/native \
    && mv /temp/src/redeclipse_server_linux /redeclipse/bin/native/redeclipse_server_linux \
    \
    && apk update \
    && apk del build-deps \
    && rm -rf /temp

# Add defaults maps and server config folder
RUN apk add --no-cache --virtual deps git ca-certificates \
    && git clone --depth 1 -b stable https://github.com/redeclipse/maps.git /redeclipse/data/maps \
    && rm -rf /redeclipse/data/maps/.git \
    && mkdir -p /re-server-config/home \
    && mkdir -p /re-server-config/package \
    && mkdir -p /re-server-config/sauer \
    && apk update \
    && apk del deps

USER redeclipse

WORKDIR /redeclipse
ENTRYPOINT ["./bin/native/redeclipse_server_linux", "-h/re-server-config/home/", "-p/re-server-config/package/", "-o/re-server-config/sauer/"]
