# Set the base image
FROM alpine

# redeclipse tag
ARG TAG
# redeclipse commit
ARG RECOMMIT

# informations
LABEL author="Iceflower S" \
      maintainer="Iceflower S" \
      email="iceflower@gmx.de" \
      description="Red Eclipse Server - $TAG" \
      re-commit="$RECOMMIT"

# Add server user and set permissions
RUN adduser -S -D redeclipse \
    && mkdir /redeclipse \
    && chown redeclipse: -R /redeclipse

# Update application repository list, create build dir, build server, move server files, create other permanent files and clean up
RUN apk update \
    && apk add --no-cache --virtual build-deps gcc g++ zlib-dev git ca-certificates freetype-dev coreutils cmake make \
    && apk add --no-cache libstdc++ \
    && git clone --depth 1 -b "$TAG" https://github.com/redeclipse/base /temp \
    \
    && mkdir /temp/build \
    && cd /temp/build \
    && cmake ../src -DBUILD_CLIENT=0 -DWANT_STEAM=0 -DWANT_DISCORD=0 \
    && make clean install -j"$(nproc)" \
    && mkdir -p /redeclipse/bin/native \
    && mv /temp/build/redeclipse_server_linux /redeclipse/bin/native/ \
    \
    && mkdir -p /redeclipse/config \
    && mv /temp/config/ /redeclipse/ \
    \
    && cd /temp \
    && git submodule update --init ./data/maps/ \
    && rm -rf ./data/maps/.git/ \
    && mkdir -p /redeclipse/data/maps \
    && mv /temp/data/maps/* /redeclipse/data/maps/ \
    \
    && apk update \
    && apk del build-deps \
    && rm -rf /temp/

# Add folder
RUN mkdir -p /re-server-config/home \
    && mkdir -p /re-server-config/package

USER redeclipse

WORKDIR /redeclipse
ENTRYPOINT ["./bin/native/redeclipse_server_linux", "-h/re-server-config/home/", "-p/re-server-config/package/"]
