# dynamical variable for other architectures, like arm64v8
ARG PREIMAGE
# Set the base image
FROM "$PREIMAGE"alpine

# redeclipse branch
ARG BRANCH

# informations
LABEL author="Iceflower S"
LABEL maintainer="Iceflower S"
LABEL email="iceflower@gmx.de"
LABEL version="1.0"
LABEL description="Red Eclipse Server - $BRANCH"

# Add server user and set permissions
RUN adduser -S -D redeclipse \
    && mkdir /redeclipse \
    && chown redeclipse: -R /redeclipse

# Update application repository list, create build dir, build server, move server files, create other permanent files and clean up
RUN apk update \
    && apk add --no-cache --virtual build-deps gcc g++ zlib-dev git ca-certificates coreutils cmake make sdl2_image-dev sdl2_mixer-dev \
    && apk add --no-cache libstdc++ \
    && git clone --depth 1 -b "$BRANCH" https://github.com/red-eclipse/base /temp \
    \
    && cd /temp \
    && make -C src -j"$(nproc)" redeclipse_server_linux install-server \
    \
    && mkdir -p /redeclipse/config \
    && mv /temp/config/ /redeclipse/ \
    && mkdir -p /redeclipse/bin/native \
    && mv /temp/src/redeclipse_server_linux /redeclipse/bin/native/redeclipse_server_linux \
    \
    && apk update \
    && apk del build-deps \
    && rm -rf /temp

# Add defaults maps and server config folder
RUN apk add --no-cache --virtual deps git ca-certificates \
    && git clone --depth 1 -b master https://github.com/red-eclipse/maps.git /redeclipse/data/maps \
    && rm -rf /redeclipse/data/maps/.git \
    && mkdir -p /re-server-config/home \
    && mkdir -p /re-server-config/package \
    && mkdir -p /re-server-config/sauer \
    && mkdir -p /home/redeclipse/re-log \
    && apk update \
    && apk del deps

USER redeclipse

WORKDIR /redeclipse
ENTRYPOINT ["./bin/native/redeclipse_server_linux", "-h/re-server-config/home", "-p/re-server-config/package", "-o/re-server-config/sauer", "-g/home/redeclipse/re-log"]
