on: [push, pull_request]
name: Build
jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd go-docker-updater
          go build -x -o updater ./cmd/updater/
